logoUrl: ENV.VITE_LOGO_URL       || "",
};export const FEATURES = {
  library:         (ENV.VITE_FEATURE_LIBRARY         ?? "true") !== "false",
  syllabus:        (ENV.VITE_FEATURE_SYLLABUS         ?? "true") !== "false",
  homework:        (ENV.VITE_FEATURE_HOMEWORK         ?? "true") !== "false",
  live_classes:    (ENV.VITE_FEATURE_LIVE_CLASSES     ?? "true") !== "false",
  tests:           (ENV.VITE_FEATURE_TESTS            ?? "true") !== "false",
  grading:         (ENV.VITE_FEATURE_GRADING          ?? "true") !== "false",
  attendance:      (ENV.VITE_FEATURE_ATTENDANCE       ?? "true") !== "false",
  grades:          (ENV.VITE_FEATURE_GRADES           ?? "true") !== "false",
  degree_progress: (ENV.VITE_FEATURE_DEGREE_PROGRESS  ?? "true") !== "false",
  gradebook:       (ENV.VITE_FEATURE_GRADEBOOK        ?? "true") !== "false",
  reports:         (ENV.VITE_FEATURE_REPORTS          ?? "true") !== "false",
  ce_hours:        (ENV.VITE_FEATURE_CE_HOURS         ?? "true") !== "false",
  cert_classes:    (ENV.VITE_FEATURE_CERT_CLASSES     ?? "true") !== "false",
  billing:         (ENV.VITE_FEATURE_BILLING          ?? "true") !== "false",
  tuition:         (ENV.VITE_FEATURE_TUITION          ?? "true") !== "false",
  certificates:    (ENV.VITE_FEATURE_CERTIFICATES     ?? "true") !== "false",
  messages:        (ENV.VITE_FEATURE_MESSAGES         ?? "true") !== "false",
  people:          (ENV.VITE_FEATURE_PEOPLE           ?? "true") !== "false",
};
